# Generated by Django 4.0.1 on 2022-01-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_breed', models.CharField(max_length=50, verbose_name='Название породы')),
                ('dog_name', models.CharField(max_length=50, verbose_name='Кличка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена щенка')),
                ('status', models.BooleanField(verbose_name='Статус продажи')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Когда последний раз обновлялись данные?')),
            ],
        ),
    ]
